[pdf-fixup] remove need for '-i' flag for input pdf

diff --git a/pdf-fixup b/pdf-fixup
--- a/pdf-fixup
+++ b/pdf-fixup
@@ -4,27 +4,13 @@ source globals
 
 ! check_command pdftk && exit 3
 
-OPTIONS=i:e:ko:s:
-LONGOPTIONS=input:,end:,keep,output:,start:
+OPTIONS=e:ko:s:
+LONGOPTIONS=end:,keep,output:,start:
 PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
 eval set -- "${PARSED}"
 
 while [ ${#} -ge 1 ]; do
   case ${1} in
-    -i|--input)
-      if ! [ -f "${2}" ]; then
-        show_error "ERROR: input '${2}' not found. Exiting."
-        exit 3
-      fi
-      if ! [[ "$(file "${2}")" =~ pdf|PDF ]]; then
-        show_error "ERROR: input '${2}' is not a PDF. Exiting."
-        exit 3
-      fi
-      INPUT="${2}"
-      NAME=${2%.*}
-      EXTENSION=${2##*.}
-      shift 2
-      ;;
     -e|--end)
       END="${2}"
       shift 2
@@ -53,6 +39,23 @@ while [ ${#} -ge 1 ]; do
       ;;
   esac
 done
+
+if [[ ${#} -ne 1 ]]; then
+  show_error "ERROR: please specify 1 input file."
+  exit 3
+else
+  if ! [ -f "${1}" ]; then
+    show_error "ERROR: input '${1}' not found. Exiting."
+    exit 3
+  fi
+  if ! [[ "$(file "${1}")" =~ pdf|PDF ]]; then
+    show_error "ERROR: input '${1}' is not a PDF. Exiting."
+    exit 3
+  fi
+  INPUT="${1}"
+  NAME=${1%.*}
+  EXTENSION=${1##*.}
+fi
 
 if ! [[ -v INPUT ]]; then
   show_error "ERROR: input not provided. Exiting."
